services:
  - type: web
    name: django-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn your_project_name.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: your_project_name.settings
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: RENDER
        value: true
